### ISSUE TITLE
TSError while trying to send a metagraph transaction with euclid dev environment and dashboard running

### ISSUE THREAD

**Issue by himmelhargott** [Constellation-Labs/sdk-developer-dashboard#3]
Now I am running out of problem solving ideas:
![image](https://github.com/Constellation-Labs/sdk-developer-dashboard/assets/123394321/fac227ab-6c0c-497c-93d4-92c99f27d170)

Please help =)

**Comment by flannoo** [comment]
Hi,

I fixed this by bumping the version of the dependency "@stardust-collective/dag4" from "^2.1.1-beta" to "^2.2.0" in the "package.json" file.

After that, run the "yarn install" command again and try to run the application again.
Sending transactions should work after that.

I'll do a pull request to have this fixed in the repo.

Hope that helps :-)
